[package]
name = "bitvec_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "bitvec_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.0"
bitvec = { version = "1.0.1", features = ["alloc"] }
